[package]
name = "basic_decrip"
version = "0.1.0"
edition = "2021"

[lib]
name = "basic_decrip_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes = "0.8"
aes-gcm = "0.10"
cbc = { version = "0.1", features = ["alloc"] }
base64 = "0.22"
hex = "0.4"
